name: test

on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4
      - name: Setup Go environment
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # pin@v5
        with:
          go-version: '1.24'
          check-latest: true
      - name: Run tests
        run: |
          go version
          git clone https://git.urbach.dev/cli/q.git --branch dev --single-branch
          cd q
          go build
          ./q build examples/hello
          ./examples/hello/hello
        shell: bash